### PR TITLE
Ensingm2 update

### PR DESCRIPTION
**Pull request by ensingm2**
So... I changed some stuff.

Couple highlights:
- AutoBuyBP implemented better
- Users now but LN if they have too much BP just to spend on WHs, (then other things too if still more after that)
- A lot of visual updates
- scriptName, version & link to github page in top right
- Added stats and settings drawers
- Link to IRC channel
- Disabled abilities are now obviously disabled visually, instead of just having a blank icon.
- Added checks to make sure the user does not go over 100% crit chance (As some people have reported you loop back to 0)
- A few other bug fixes (feel free to look at my commits)

You'll probably want to test out the branch first:

https://github.com/ensingm2/MonsterMinigameWormholeWarp/raw/master/autoplay.noUpdate.user.js

Merge this into master if you want. Or don't. Your call.

### CODE REVIEW

**Comment by HoaxIT** [comment]
FUCK IT SHIP IT

**Comment by ensingm2** [comment]
RIP

**Comment by chauffer** [comment]
ship it

**Pull request merged**
