### PR TITLE
Honking Intensifies :3c

### PR DESCRIPTION
**Pull request by GoomiChan**
On boss levels Chen gets very intense and ups her Honking game
Preview here: http://www.gfycat.com/AggressiveImpressionableGaur
Thanks to VegetableJuice for help with the images.

### CODE REVIEW

**Comment by jwyly** [comment]
Squashing is your friend :smile:

**Comment by GoomiChan** [comment]
Is there really a need to squash for 5 commits?

**Comment by jwyly** [comment]
Sorry maybe it's not clear, but I'm no admin.

For me, should be squashed but I have no opinion here. Just a bit of teasing is all best of luck

**Comment by GoomiChan** [comment]
Just to note, been running this for 5+ hours now without issue.

**Comment by Novex** [comment]
what is this?

**Comment by GoomiChan** [comment]
On a % 100 level, when wormholes are being charge for a jump it replaces Chen(the one who Honks) with a gif of her getting more intense.
What you see in the attached video in the first comment is what happens on a % 100 level, on any other it Looks just like the old "Honk Honk?" option I added before.

Here is the video again of what this does if "Honk Honk?" is checked and its on a % 100 level http://www.gfycat.com/AggressiveImpressionableGaur

If anything else is unclear let me know :>

**Comment by DannyDaemonic** [comment]
Since I don't think I can remove the honk honk option at this point, and since this is just an update to that, I'm going to merge it.


@GoomiChan In the future, don't manually update the version. This creates a conflict when we have also changed the version. Git doesn't understand versions and simply sees a change you tried to make removed a line that doesn't exist anymore ("version 7.0.2"). I will have to manually merge this in.

**Comment by GoomiChan** [comment]
Originally I wasn't going to increment the version but in my previous PR I was asked to so I figured I would do the same this time.

Glad its making it in tho :>

**Comment by DannyDaemonic** [comment]
I'm trying to modify the branch and submit a new pull request but it will
happen faster if you resubmit the pull request without the version changes.

**Comment by GoomiChan** [comment]
@DannyDaemonic And done see #65

**Comment by DannyDaemonic** [comment]
Sorry about the confusion over the version number. Generally altering version numbers just causes a conflict. I don't see a problem with bumping the version number later anyway.

**Comment by GoomiChan** [comment]
No worrys and I can totally understand that, its alot less hassle when things just merge cleanly.

**Pull request closed without merging**
