### PR TITLE
add critical tv smacking feature back in

### PR DESCRIPTION
**Pull request by tubersan**
importance: verily

### CODE REVIEW

**Comment by Novex** [comment]
I have no idea what this is meant to do?

**Comment by DannyDaemonic** [comment]
I don't get the reference for "smack tv", and I hate seeing the words there, but this is actually kind of cool. The canvas (tv screen) has a filter on it to make it look like there are scanlines. This makes it so when you click the little steam logo it changes that filter. It has a couple different effects you can cycle through.

**Comment by DannyDaemonic** [comment]
Although this patch doesn't seem to contain that code. I think maybe tubersan submitted the wrong patch, or the reversions have confused git's diff.

**Comment by DannyDaemonic** [comment]
Sorry, but something seems to have screwed up your pull request? I put part of it back. If you intended on adding anything else that I missed please open a new pull request.

**Comment by tubersan** [comment]
Mmh, I had changed the code so that the Smack TV words are next to the TV and not on the little steam logo anymore, it should look something like this: https://i.nope.bz/05XK.png (notice the "Smack TV" on the left and right of the screen)
Should I submit another PR that puts the button/link for smacking in that place instead of where it is now?

**Pull request closed without merging**
