### PR TITLE
Add script to update version and store it in a JSON for update checking

### PR DESCRIPTION
**Pull request by kategray**
Any possibility of getting a version.json so that I can use it with the updater I'm writing?

### CODE REVIEW

**Comment by HoaxIT** [comment]
Merged!

**Comment by kategray** [comment]
Thank you!

I had to use tampermonkey/greasemonkey API calls in order to deal with the security restrictions.  Valve sets a header that limits the domain to run from.  The security being what it is, I can't figure out how to force an update even if I want to.

I made a sample alert notifier and am doing testing with it.  It's at https://raw.githubusercontent.com/KateGray/UpdateBitchTest/master/update.bitch.js .  If it passes testing, I'll clean it up and incorporate it, then do a push request. 

It's designed to be attention-grabbing, so it takes over the whole screen.

screen shot 2015-06-18 at 10 10 48 pm

**Comment by kategray** [comment]
@HoaxIT What do you think of this approach?

https://github.com/kategray/UpdateBitchTest/blob/1444bca3dc0ec9033097fdffb9afdbc2c54d12d1/update.bitch.js

Yeah, it's evil.  Yeah, it uses eval().  It does, however, auto-reload the script when an update happens.

**Comment by HoaxIT** [comment]
@kategray went to sleep, i loved the idea, seems it's merged now :)

**Comment by kategray** [comment]
Figured out how to do it without Eval()

**Pull request merged**
